name = "datahop"
[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
go_version = "1.17"
module_path = "github.com/datahop/test-plans/datahop"
exec_pkg = "."

[builders."exec:go"]
enabled = true
module_path = "github.com/datahop/test-plans/datahop"

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name= "connection"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name= "private-connection"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name= "group"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name= "content-distribution"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap1"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap1-10"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap1-100"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap1-rand"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap1-0-one"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap1-10-one"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap1-100-one"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap1-rand-one"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap1-0-ten"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap1-10-ten"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap1-100-ten"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap1-rand-ten"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap1-0-hund"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap1-10-hund"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap1-100-hund"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap1-rand-hund"
instances = { min = 1, max = 1000, default = 2 }


[[testcases]]
name = "bitswap2"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap2-10"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap2-100"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap2-rand"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap2-0-one"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap2-10-one"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap2-100-one"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap2-rand-one"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap2-0-ten"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap2-10-ten"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap2-100-ten"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap2-rand-ten"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap2-0-hund"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap2-10-hund"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap2-100-hund"
instances = { min = 1, max = 1000, default = 2 }

[[testcases]]
name = "bitswap2-rand-hund"
instances = { min = 1, max = 1000, default = 2 }



